import type {ReactNode} from 'react';
import {GrimoireSelectionPanel} from './GrimoireSelectionPanel';
export function GrimoireHandoffView({title,rows,children,completed,busy,ready,onReset,onConfirm,onContinue,confirmLabel='선택 확정',resetLabel='초기화',showReset=true,continueLabel='다음 →',onDecline,declineLabel='선택하지 않음'}:{title:ReactNode;rows:{label:string;value:ReactNode}[];children?:ReactNode;completed:boolean;busy:boolean;ready:boolean;onReset:()=>void;onConfirm:()=>void;onContinue:()=>void;confirmLabel?:string;resetLabel?:string;showReset?:boolean;continueLabel?:string;onDecline?:()=>void;declineLabel?:string}){
 return <GrimoireSelectionPanel title={title} completed={completed} reset={!completed&&showReset?<button type="button" disabled={busy} onClick={onReset}>{resetLabel}</button>:null} action={completed?<button type="button" className="issue116PrimaryAction issue116NextAction" disabled={busy} onClick={onContinue}>{continueLabel}</button>:<><button type="button" className="issue116PrimaryAction" disabled={busy||!ready} onClick={onConfirm}>{confirmLabel}</button>{onDecline&&<button type="button" disabled={busy} onClick={onDecline}>{declineLabel}</button>}</>}><dl>{rows.map((row,i)=><div key={i}><dt>{row.label}</dt><dd>{row.value}</dd></div>)}</dl>{children}</GrimoireSelectionPanel>;
}
export function GrimoireNotificationPrompt({kind,playerLabel,players=[],sequence=1,total=1,onReveal}:{kind:'madnessAssignment'|'characterChange'|'evilTwinPair'|'nightwatchmanInformation';playerLabel:string;players?:{playerId:string;seat:number;name:string}[];sequence?:number;total?:number;onReveal:()=>void}) {
 if(kind==='nightwatchmanInformation')return <section className="snakeCharmerRevealPrompt" role="dialog" aria-label="야경꾼 통지"><strong>야경꾼 통지</strong><p>{playerLabel}</p><button type="button" onClick={onReveal}>공개</button></section>;
 if(kind==='evilTwinPair')return <section className="snakeCharmerRevealPrompt evilTwinRevealPrompt" role="dialog" aria-label="쌍둥이 확인 안내"><strong>쌍둥이 확인</strong><div className="evilTwinRevealPromptPlayers">{players.map(p=><span key={p.playerId}>[{p.seat}번 {p.name}]</span>)}</div><button type="button" onClick={onReveal}>공개</button></section>;
 if(kind==='madnessAssignment')return <section className="cerenovusMadnessRevealPrompt" role="dialog" aria-label="집착 안내"><strong>집착 안내</strong><p>{playerLabel}</p><button type="button" onClick={onReveal}>공개</button></section>;
 return <section className="snakeCharmerRevealPrompt" role="dialog" aria-label={`직업 변경 안내 ${sequence}/${total}`}><strong>직업이 변경됩니다</strong><p>{playerLabel}</p><button type="button" onClick={onReveal}>공개</button></section>;
}
