import presentation from '../../src/custom/authoring/characterPresentation.json' with { type: 'json' };
/** Authored requirements, independent of runtime output. Pool membership is never evidence. */
const rows = [
  ['washerwoman','G01','세탁부','두 후보 중 지정한 마을주민의 실제 근거가 존재한다.','Spy 등록, 취함/중독, 시작 정보 획득','issue209MixedFirstNight.test.ts'],
  ['librarian','G01','사서','두 후보와 외지인 정보를 공개한다.','외지인 없음, Recluse 등록, 순서 밖 획득','issue209MixedFirstNight.test.ts'],
  ['investigator','G01','수사관','두 후보와 하수인 정보를 공개한다.','Recluse 등록, 취함/중독','issue209MixedFirstNight.test.ts'],
  ['chef','G01','요리사','좌석 원형에서 악한 이웃 쌍의 수를 확인한다.','각 인접 쌍의 독립 등록, 순서 변경과 중독','issue209Provenance.test.ts'],
  ['empath','G01','초공감자','살아 있는 양옆 이웃의 악한 수를 공개한다.','이웃 사망, 등록, 취함/중독','issue209MixedFirstNight.test.ts'],
  ['fortuneTeller','G01','점쟁이','선택한 두 명의 악마·빨간 청어 판정을 공개한다.','빨간 청어, Recluse, 능력 instance별 준비','issue209MixedFirstNight.test.ts'],
  ['undertaker','G02','장의사','전날 처형된 캐릭터의 당시 근거를 사용한다.','처형 없음, 사망한 관찰자, 이후 정체·중독 변화','issue225Nights.test.ts'],
  ['monk','G02','수도사','선택한 타인의 악마 공격을 막는다.','자기 선택 거부, 다음 밤 만료, 취함/중독','issue222Actions.test.ts'],
  ['ravenkeeper','G02','까마귀지기','밤에 사망한 직후 대상 캐릭터 정보를 공개한다.','낮 사망 비발동, 후속 도중 복원, 원인과 함께 Undo','issue225Nights.test.ts'],
  ['virgin','G02','성결자','첫 지명에서 마을주민 지명자를 처형한다.','비마을주민 첫 지명, 취함/중독과 사용 소진','issue223Day.test.ts'],
  ['slayer','G02','처단자','낮 선택으로 악마를 죽이고 사용을 소진한다.','비악마, Recluse 판단, 취함/중독, 승계','issue223Day.test.ts'],
  ['soldier','G02','군인','정상 능력이 있는 동안 악마 공격으로 죽지 않는다.','취함/중독, 주정뱅이 Shown, 능력 상실','issue222Actions.test.ts'],
  ['mayor','G02','시장','악마 공격을 다른 대상으로 돌리는 판단을 적용한다.','대신 공격 대상의 보호, 직접 사망, 3인 무처형 종료','issue222Actions.test.ts'],
  ['butler','G01','집사','선택한 주인의 투표에 종속해 유효표를 계산한다.','주인 미투표 시 표 제외, 다음 밤 교체, 유령표','issue223Day.test.ts'],
  ['drunk','G01','주정뱅이','Shown 마을주민 정보가 실제 능력을 부여하지 않는다.','참/거짓 전달의 수학자 차이, 획득·모의 출처','issue213Jinxes.test.ts'],
  ['recluse','G04','은둔자','현자 정보에서 합법적인 악마 오등록 판단을 보존한다.','중독·사망·상실·획득 당시 등록, 비적용','issue213Jinxes.test.ts'],
  ['saint','G01','성자','정상 상태에서 처형되면 악의 승리 확인으로 진행한다.','비처형 사망, 취함/중독','issue223Day.test.ts'],
  ['poisoner','G01','독살범','선택한 대상의 능력 실패와 효과 기간을 확인한다.','자기 중독, 다음 밤 교체, 원인 능력 상실','issue209MixedFirstNight.test.ts'],
  ['spy','G01','첩자','확정 당시 마도서 정보를 공개하고 등록 판단을 확인한다.','Townsfolk/Outsider 등록, 과거 공개 고정','issue209MixedFirstNight.test.ts'],
  ['scarletWoman','G02','탕녀','조건을 만족하는 악마 사망에서 악마로 승계한다.','인원·중독 경계, 임프 우선순위, Fang Gu 이동 비적용','issue213Jinxes.test.ts'],
  ['baron','G01','남작','실제 배정된 남작이 외지인 수를 2 늘린 Setup을 검증한다.','후보 풀만 포함된 경우, 사망·변경 후 분포 비소급','issue220T11Distribution.test.ts'],
  ['imp','G02','임프','선택한 대상을 공격하고 필요한 사망 후속을 처리한다.','보호·시장, 자살 승계와 탕녀 우선순위','issue222Actions.test.ts'],
  ['clockmaker','G02','시계공','악마와 가장 가까운 하수인의 좌석 거리를 공개한다.','등록, 취함/중독, 획득 시점','issue209MixedFirstNight.test.ts'],
  ['dreamer','G03','꿈꾸는 자','좋은 캐릭터와 악한 캐릭터 한 쌍을 전달한다.','Vortox 거짓, 등록, 취함/중독','issue209MixedFirstNight.test.ts'],
  ['snakeCharmer','G04','뱀 조련사','악마 선택 시 캐릭터·진영 교환과 이전 악마의 중독을 확인한다.','비악마 선택, 취함/중독, 남은 순서에서 해당 밤 공격','issue222NightUI.test.ts'],
  ['mathematician','G01','수학자','이번 관찰 구간의 다른 능력에 의한 오작동 근거를 확인한다.','Drunk 참/거짓, 낮 근거, 새벽 초기화, 소급 출처','issue213Jinxes.test.ts'],
  ['flowergirl','G03','꽃팔이 소녀','지난 낮 악마의 투표 기록에 근거한 정보를 공개한다.','Vortox, 당시 정체·등록, 이후 정체 변경','issue225Nights.test.ts'],
  ['townCrier','G03','포고꾼','지난 낮 하수인의 지명 기록에 근거한 정보를 공개한다.','Vortox, 지명 없음, 당시 정체·등록','issue225Nights.test.ts'],
  ['oracle','G03','예언자','죽은 악한 플레이어의 수를 공개한다.','Vortox, 죽은 Recluse, 정체·진영 변화','issue225Nights.test.ts'],
  ['savant','G03','백치천재','낮 두 진술의 판단을 기록하고 보존한다.','Vortox 두 거짓, 취함/중독, 하루 사용','issue223Day.test.ts'],
  ['seamstress','G03','재봉사','두 사람의 진영 비교를 전달하고 사용을 소진한다.','Vortox, 미사용 연기, 다음 밤 재사용 거부','issue225Nights.test.ts'],
  ['philosopher','G04','철학자','선택한 선한 능력을 실제 출처로 획득한다.','기존 보유자 취함, 실패 모의, 순서 전후·시작 정보','issue209MixedFirstNight.test.ts'],
  ['artist','G03','화가','낮 질문·답변 판단을 기록하고 사용을 소진한다.','Vortox 거짓, 취함/중독, 획득 출처','issue223Day.test.ts'],
  ['juggler','G03','곡예사','첫날 낮 판단 기록을 다음 밤 정보로 전달한다.','Vortox, 기록 없음, 획득 시점','issue225Nights.test.ts'],
  ['sage','G04','현자','악마에 의한 밤 사망 후 두 후보 정보를 공개한다.','Recluse Jinx, 중독, 사망 원인과 확정 정보 보존','issue213Jinxes.test.ts'],
  ['mutant','G03','변종','광기 위반 판단과 선택적 처형을 처리한다.','비위반·처형하지 않음, 취함/중독, 종료와 Undo','issue223Day.test.ts'],
  ['sweetheart','G02','사랑꾼','사망 당시 능력 출처로 취한 대상을 정하고 유지한다.','밤·낮 사망, 취함/중독, 사망 후 정체 변경','issue223Day.test.ts'],
  ['barber','G02','이발사','사망 후 악마가 선택한 두 사람의 캐릭터를 교환한다.','거절, 순서 전후·즉시 처리, 연속 통지와 Undo','issue222Actions.test.ts'],
  ['klutz','G03','얼뜨기','사망 후 선택 판단과 필요한 종료를 처리한다.','선/악 대상, 취함/중독, 사망 당시 진영','issue223Day.test.ts'],
  ['evilTwin','G03','사악한 쌍둥이','쌍둥이 정보와 좋은 쌍둥이 처형 종료를 확인한다.','악마 사망 시 승리 제한, 능력 상실·취함/중독','issue209MixedFirstNight.test.ts'],
  ['witch','G02','마녀','저주받은 지명자의 사망 후 같은 지명을 이어간다.','3인 이하, 취함/중독, 다음 밤 만료','issue223Day.test.ts'],
  ['cerenovus','G02','세레노버스','지정 캐릭터 광기 통지·판단·처형을 처리한다.','비위반·처형하지 않음, 취함/중독, 기간 만료','issue223Day.test.ts'],
  ['pitHag','G04','마귀할멈','대상의 캐릭터를 변경하고 새 능력과 통지를 처리한다.','악마 생성 필수 사망, 순서 전후 획득, 진영 유지','issue222Actions.test.ts'],
  ['fangGu','G04','팡 구','첫 유효 외지인 공격이 악한 팡 구 이동을 만든다.','탕녀 비승계, 두 번째 외지인 공격, 일반 사망 승계','issue213Jinxes.test.ts'],
  ['vigormortis','G05','비고르모르티스','살해한 하수인의 능력과 선택한 이웃 중독을 유지한다.','일반 대상 사망, 유지 능력 중독, 악마 상실·사망 해제','issue225Nights.test.ts'],
  ['noDashii','G05','노 다시','가장 가까운 마을주민 두 명의 중독을 계산한다.','외지인·악한 좌석 건너뜀, 정체 변화, 원인 상실','issue225Nights.test.ts'],
  ['vortox','G03','보르톡스','마을주민 거짓 정보와 무처형 패배를 적용한다.','비정보 능력, Drunk 모의, 낮 정보·등록·효과 상실','issue209Provenance.test.ts'],
] as const;

export const characterRequirements = rows.map(([characterId, gameId, _nameKo, expectedKo, branches, existingEvidence]) => ({
  id: `character-${characterId}`, characterId, gameId, nameKo: (presentation as Record<string, {label:string}>)[characterId].label, expectedKo,
  majorBranchesKo: branches.split(', '),
  source: `https://wiki.bloodontheclocktower.com/${characterId === 'pitHag' ? 'Pit-Hag' : characterId.replace(/([a-z])([A-Z])/g, '$1_$2').replace(/^./, c => c.toUpperCase())}`,
  existingEvidence, userResult: 'unverified', deviceResult: 'unverified',
}));

export const sharedRequirements = [
  ['orders', '두 밤 독립 편집·복원과 시나리오 파일 왕복'],
  ['setup', '실제 배정·분포·Shown·bluff와 후보 풀 분리'],
  ['three-nights', '첫날 밤→낮→둘째 밤→낮→셋째 밤 이상 연속 진행'],
  ['pending-restore', '사망 후속 미완료 시 파일·새 세션 복원'],
  ['frozen-reveal', '현재 정체·상태가 변해도 확정 당시 공개 유지'],
  ['causal-undo', '원인·후속 묶음과 이후 독립 행동 Undo 구분'],
  ['stale-command', '오래된 명령과 Undo 확인 거부'],
  ['invalid-file', '변조·불완전 파일 거부와 정상 저장본 보존'],
  ['save-retry', '저장 실패·재시도·늦은 응답과 중복 방지'],
  ['day-votes', '지명·집사 투표·유령표·동률·처형 없음'],
  ['end-game', '승리 확인·종료 후 행동 제한'],
  ['jinx-drunk-math', 'Drunk–Mathematician 적용·비적용'],
  ['jinx-recluse-sage', 'Recluse–Sage 적용·비적용'],
  ['jinx-scarlet-fang', 'Scarlet Woman–Fang Gu 적용·비적용'],
  ['reference', 'PDF/직업 화면의 후보 풀 Jinx 일치와 비밀 제외'],
  ['reference-layout', '징크스 없음·여러 개·긴 문구·한글·페이지 나눔'],
  ['official-regression', '공식 TB·SnV 진행·저장·공개 경계'],
  ['device', '모바일/iPad/데스크톱 조작과 실제 시스템 인쇄·오프라인'],
].map(([id, expectedKo]) => ({ id: `shared-${id}`, expectedKo, userResult: 'unverified', deviceResult: 'unverified' }));
