import type {ActionAdapter} from './registry';
export const sectsAndVioletsActions={
 'snakeCharmer.choosePlayer':{stage:'action',inputView:'players',acceptedInputs:['playerIds'],selectionContract:'direct',completionContract:{afterSelection:'confirm',continuationEntry:'select'},revealView:'identity',revealOpen:'notification',closeDestination:'board',cancellation:'discardInput'},
 'witch.chooseCursedPlayer':{selectionLabel:'저주 대상 선택',stage:'action',inputView:'players',acceptedInputs:['playerIds'],selectionContract:'direct',completionContract:{afterSelection:'confirm',continuationEntry:'select'},revealView:'none',revealOpen:'result',closeDestination:'progress',cancellation:'discardInput'},
 'evilTwin.assignTwin':{selectionLabel:'쌍둥이 선택',stage:'preparation',inputView:'players',acceptedInputs:['playerIds'],selectionContract:'direct',completionContract:{afterSelection:'confirm',continuationEntry:'select'},revealView:'none',revealOpen:'result',closeDestination:'board',cancellation:'discardInput'},
 'evilTwin.learnTwin':{stage:'delivery',inputView:'none',acceptedInputs:['none'],selectionContract:'none',completionContract:{afterSelection:'edit',continuationEntry:'prepare'},revealView:'twin',revealOpen:'notification',closeDestination:'board',cancellation:'discardInput'},
 'clockmaker.learnSteps':{stage:'delivery',inputView:'information',acceptedInputs:['none'],selectionContract:'none',completionContract:{afterSelection:'edit',continuationEntry:'edit'},revealView:'snv',revealOpen:'preview',closeDestination:'progress',cancellation:'discardInput'},
 'mathematician.learnCount':{stage:'delivery',inputView:'information',acceptedInputs:['none'],selectionContract:'none',completionContract:{afterSelection:'edit',continuationEntry:'edit'},revealView:'snv',revealOpen:'preview',closeDestination:'progress',cancellation:'discardInput'},
 'dreamer.learnCharacters':{stage:'delivery',inputView:'information',acceptedInputs:['playerIds'],selectionContract:'information',completionContract:{afterSelection:'edit',continuationEntry:'select'},revealView:'snv',revealOpen:'preview',closeDestination:'progress',cancellation:'discardInput'},
 'seamstress.compareAlignments':{stage:'delivery',inputView:'information',acceptedInputs:['playerIds'],selectionContract:'information',completionContract:{afterSelection:'edit',continuationEntry:'select'},revealView:'snv',revealOpen:'preview',closeDestination:'progress',cancellation:'discardInput'},
 'philosopher.chooseAbility':{stage:'action',inputView:'ability',acceptedInputs:['characterIds'],selectionContract:'none',completionContract:{afterSelection:'edit',continuationEntry:'edit'},revealView:'identity',revealOpen:'notification',closeDestination:'board',cancellation:'discardInput'},
 'cerenovus.assignMadness':{selectionLabel:'집착 지정',stage:'action',inputView:'madness',acceptedInputs:['madnessAssignment'],selectionContract:'direct',completionContract:{afterSelection:'confirm',continuationEntry:'select'},revealView:'madness',revealOpen:'notification',closeDestination:'board',cancellation:'discardInput'},
 'mutant.resolveMadnessExecution':{stage:'action',inputView:'execution',acceptedInputs:['executionDecision'],selectionContract:'none',completionContract:{afterSelection:'edit',continuationEntry:'edit'},revealView:'none',revealOpen:'result',closeDestination:'progress',cancellation:'discardInput'},
} as const satisfies Record<string,ActionAdapter>;
