import type {ActionAdapter} from './registry';
export const troubleBrewingActions={
 'fortuneTeller.assignRedHerring':{stage:'preparation',inputView:'players',acceptedInputs:['playerIds'],selectionContract:'direct',completionContract:{afterSelection:'confirm',continuationEntry:'select'},revealView:'none',revealOpen:'result',closeDestination:'board',cancellation:'discardInput'},
 'washerwoman.prepareInformation':{stage:'preparation',inputView:'setup',acceptedInputs:['setupInfo'],selectionContract:'setup',completionContract:{afterSelection:'edit',continuationEntry:'select'},revealView:'none',revealOpen:'result',closeDestination:'progress',cancellation:'discardInput'},
 'librarian.prepareInformation':{stage:'preparation',inputView:'setup',acceptedInputs:['setupInfo'],selectionContract:'setup',completionContract:{afterSelection:'edit',continuationEntry:'select'},revealView:'none',revealOpen:'result',closeDestination:'progress',cancellation:'discardInput'},
 'investigator.prepareInformation':{stage:'preparation',inputView:'setup',acceptedInputs:['setupInfo'],selectionContract:'setup',completionContract:{afterSelection:'edit',continuationEntry:'select'},revealView:'none',revealOpen:'result',closeDestination:'progress',cancellation:'discardInput'},
 'drunk.assignShownCharacter':{stage:'preparation',inputView:'ability',acceptedInputs:['characterIds'],selectionContract:'none',completionContract:{afterSelection:'edit',continuationEntry:'edit'},revealView:'none',revealOpen:'result',closeDestination:'progress',cancellation:'discardInput'},
 'poisoner.choosePoisonTarget':{stage:'action',inputView:'players',acceptedInputs:['playerIds'],selectionContract:'direct',completionContract:{afterSelection:'confirm',continuationEntry:'select'},revealView:'none',revealOpen:'result',closeDestination:'progress',cancellation:'discardInput'},
 'butler.chooseMaster':{stage:'action',inputView:'players',acceptedInputs:['playerIds'],selectionContract:'direct',completionContract:{afterSelection:'confirm',continuationEntry:'select'},revealView:'none',revealOpen:'result',closeDestination:'progress',cancellation:'discardInput'},
 'washerwoman.learnTownsfolk':{stage:'delivery',inputView:'information',acceptedInputs:['none'],selectionContract:'none',completionContract:{afterSelection:'edit',continuationEntry:'prepare'},revealView:'tb',revealOpen:'preview',closeDestination:'progress',cancellation:'discardInput'},
 'librarian.learnOutsider':{stage:'delivery',inputView:'information',acceptedInputs:['none'],selectionContract:'none',completionContract:{afterSelection:'edit',continuationEntry:'prepare'},revealView:'tb',revealOpen:'preview',closeDestination:'progress',cancellation:'discardInput'},
 'investigator.learnMinion':{stage:'delivery',inputView:'information',acceptedInputs:['none'],selectionContract:'none',completionContract:{afterSelection:'edit',continuationEntry:'prepare'},revealView:'tb',revealOpen:'preview',closeDestination:'progress',cancellation:'discardInput'},
 'chef.learnEvilPairs':{stage:'delivery',inputView:'information',acceptedInputs:['none'],selectionContract:'none',completionContract:{afterSelection:'edit',continuationEntry:'edit'},revealView:'tb',revealOpen:'preview',closeDestination:'progress',cancellation:'discardInput'},
 'empath.learnEvilNeighbors':{stage:'delivery',inputView:'information',acceptedInputs:['none'],selectionContract:'none',completionContract:{afterSelection:'edit',continuationEntry:'edit'},revealView:'tb',revealOpen:'preview',closeDestination:'progress',cancellation:'discardInput'},
 'fortuneTeller.checkDemon':{stage:'delivery',inputView:'information',acceptedInputs:['playerIds'],selectionContract:'information',completionContract:{afterSelection:'edit',continuationEntry:'select'},revealView:'tb',revealOpen:'preview',closeDestination:'progress',cancellation:'discardInput'},
 'spy.inspectGrimoire':{stage:'delivery',inputView:'information',acceptedInputs:['none'],selectionContract:'none',completionContract:{afterSelection:'edit',continuationEntry:'edit'},revealView:'spy',revealOpen:'preview',closeDestination:'progress',cancellation:'discardInput'},
} as const satisfies Record<string,ActionAdapter>;
